<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pod</string>
	</array>
	<key>name</key>
	<string>Perl POD</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^=(pod|cut|over|item|back)\W*$</string>
			<key>name</key>
			<string>keyword.other.documentation.perl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^=(head[1-4]|item)\W{1,}(.+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.header.other.documentation.perl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>keyword.valued.other.documentation.perl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>[IBCLEFX]&lt;([\w ]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.documentation.perl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>support.function.documentation.perl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^=item\W*(\w*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.documentation.perl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>keyword.other.documentation.perl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^=back.*\w{1,}</string>
			<key>name</key>
			<string>invalid.illegal.other.documentation.perl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^=over.*\w{1,}</string>
			<key>name</key>
			<string>invalid.deprecated.other.documentation.perl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^=\W*\w+</string>
			<key>name</key>
			<string>invalid.illegal.documentation.perl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.documentation.perl</string>
	<key>uuid</key>
	<string>68748f9d-6fd9-4ac6-897f-b8879b02b499</string>
</dict>
</plist>
